# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addUser_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddUser(object):
    def setupUi(self, AddUser):
        AddUser.setObjectName("AddUser")
        AddUser.resize(352, 112)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddUser.sizePolicy().hasHeightForWidth())
        AddUser.setSizePolicy(sizePolicy)
        self.addUserBox = QtWidgets.QGroupBox(AddUser)
        self.addUserBox.setGeometry(QtCore.QRect(10, 10, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.addUserBox.setFont(font)
        self.addUserBox.setObjectName("addUserBox")
        self.addUserEdit = QtWidgets.QLineEdit(self.addUserBox)
        self.addUserEdit.setGeometry(QtCore.QRect(10, 20, 311, 31))
        self.addUserEdit.setObjectName("addUserEdit")
        self.addUser = QtWidgets.QPushButton(AddUser)
        self.addUser.setGeometry(QtCore.QRect(10, 80, 151, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addUser.setFont(font)
        self.addUser.setObjectName("addUser")
        self.cancel = QtWidgets.QPushButton(AddUser)
        self.cancel.setGeometry(QtCore.QRect(200, 80, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancel.setFont(font)
        self.cancel.setObjectName("cancel")

        self.retranslateUi(AddUser)
        QtCore.QMetaObject.connectSlotsByName(AddUser)

    def retranslateUi(self, AddUser):
        _translate = QtCore.QCoreApplication.translate
        AddUser.setWindowTitle(_translate("AddUser", "Dialog"))
        self.addUserBox.setTitle(_translate("AddUser", "AddUserGroup"))
        self.addUser.setText(_translate("AddUser", "addUser"))
        self.cancel.setText(_translate("AddUser", "cancel"))
