rus = {'titleWindow': 'Тренажер по математике',
       'exitButton': 'Выход',
       'mainLabel': 'Тренажер по математике',
       'modeGroup': 'Режим',
       'actionGroup': 'Действия',
       'homeButton': 'Главное меню',
       'examRButton': 'Проверка',
       'teachRButton': 'Обучение',
       'addCheckBox': 'Сложение',
       'subCheckBox': 'Деление',
       'multCheckBox': 'Умножение',
       'divCheckBox': 'Вычитание',
       'nameCheckBox': 'Имя',
       'startButton': 'Старт',
       'statButton': 'Статистика',
       'wrongAnswer': 'Не правильно. Правильный ответ ',
       'noAction': 'Не выбрано действие'
       }

eng = {'titleWindow': 'Mathematics simulator',
       'exitButton': 'Exit',
       'mainLabel': 'Mathematics simulator',
       'modeGroup': 'Mode',
       'actionGroup': 'Actions',
       'homeButton': 'Main menu',
       'examRButton': 'Check',
       'teachRButton': 'Training',
       'addCheckBox': 'Addition',
       'subCheckBox': 'Subtraction',
       'multCheckBox': 'Multiplication',
       'divCheckBox': 'Division',
       'nameCheckBox': 'Name',
       'startButton': 'Start',
       'statButton': 'Statistics',
       'wrongAnswer': 'Wrong answer. Correct answer ',
       'noAction': 'No action select'
       }

languages = {'Русский': rus,
             'English': eng}