rus = {'titleWindow': 'Тренажер по математике',
       'exitButton': 'Выход',
       'mainLabel': 'Тренажер по математике',
       'modeGroup': 'Режим',
       'actionGroup': 'Действия',
       'homeButton': 'Главное меню',
       'examRButton': 'Проверка',
       'teachRButton': 'Обучение',
       'addCheckBox': 'Сложение',
       'divCheckBox': 'Деление',
       'multCheckBox': 'Умножение',
       'subCheckBox': 'Вычитание',
       'nameCheckBox': 'Имя',
       'startButton': 'Старт',
       'statButton': 'Статистика',
       'wrongAnswer': 'Не правильно. Правильный ответ',
       'noAction': 'Не выбрано действие',
       'resultGroupBox': 'Результаты',
       'labelRightCount': 'Правильно',
       'labelWrongCount': 'Не правильно',
       'userGroupBox': 'Имя',
       'addUserGroup': 'Введите имя пользователя',
       'addUser': 'Добавить',
       'cancel': 'Отмена',
       'existUserText': 'Пользователь существует'
       }

eng = {'titleWindow': 'Mathematics simulator',
       'exitButton': 'Exit',
       'mainLabel': 'Mathematics simulator',
       'modeGroup': 'Mode',
       'actionGroup': 'Actions',
       'homeButton': 'Main menu',
       'examRButton': 'Check',
       'teachRButton': 'Training',
       'addCheckBox': 'Addition',
       'divCheckBox': 'Division',
       'multCheckBox': 'Multiplication',
       'subCheckBox': 'Subtraction',
       'nameCheckBox': 'Name',
       'startButton': 'Start',
       'statButton': 'Statistics',
       'wrongAnswer': 'Wrong answer. Correct answer',
       'noAction': 'No action select',
       'resultGroupBox': 'Result',
       'labelRightCount': 'Right',
       'labelWrongCount': 'Wrong',
       'userGroupBox': 'Name',
       'addUserGroup': 'Enter username',
       'addUser': 'Add',
       'cancel': 'Cancel',
       'existUserText': 'User exist'
       }

languages = {'Русский': rus,
             'English': eng}