# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        self.homeButton = QtWidgets.QPushButton(Dialog)
        self.homeButton.setGeometry(QtCore.QRect(10, 440, 100, 30))
        self.homeButton.setObjectName("homeButton")
        self.mainLabel = QtWidgets.QLabel(Dialog)
        self.mainLabel.setGeometry(QtCore.QRect(130, 10, 380, 35))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.mainLabel.setFont(font)
        self.mainLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mainLabel.setAutoFillBackground(False)
        self.mainLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mainLabel.setObjectName("mainLabel")
        self.exitButton = QtWidgets.QPushButton(Dialog)
        self.exitButton.setGeometry(QtCore.QRect(530, 440, 100, 30))
        self.exitButton.setObjectName("exitButton")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(390, 441, 130, 28))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "lang1")
        self.comboBox.addItem("")
        self.comboBox.setItemText(1, "lang2")
        self.labelLanguage = QtWidgets.QLabel(Dialog)
        self.labelLanguage.setGeometry(QtCore.QRect(260, 439, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelLanguage.setFont(font)
        self.labelLanguage.setObjectName("labelLanguage")
        self.lineLabel = QtWidgets.QFrame(Dialog)
        self.lineLabel.setGeometry(QtCore.QRect(20, 50, 601, 20))
        self.lineLabel.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineLabel.setObjectName("lineLabel")
        self.techRButton = QtWidgets.QRadioButton(Dialog)
        self.techRButton.setGeometry(QtCore.QRect(360, 120, 160, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.techRButton.setFont(font)
        self.techRButton.setObjectName("techRButton")
        self.examRButton = QtWidgets.QRadioButton(Dialog)
        self.examRButton.setGeometry(QtCore.QRect(130, 120, 160, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.examRButton.setFont(font)
        self.examRButton.setCheckable(True)
        self.examRButton.setChecked(True)
        self.examRButton.setObjectName("examRButton")
        self.modeLabel = QtWidgets.QLabel(Dialog)
        self.modeLabel.setGeometry(QtCore.QRect(130, 70, 380, 35))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.modeLabel.setFont(font)
        self.modeLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.modeLabel.setAutoFillBackground(False)
        self.modeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.modeLabel.setObjectName("modeLabel")
        self.lineLabel_2 = QtWidgets.QFrame(Dialog)
        self.lineLabel_2.setGeometry(QtCore.QRect(20, 150, 601, 20))
        self.lineLabel_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineLabel_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineLabel_2.setObjectName("lineLabel_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.homeButton.setText(_translate("Dialog", "homeButton"))
        self.mainLabel.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">mainLabel</p></body></html>"))
        self.exitButton.setText(_translate("Dialog", "exitButton"))
        self.labelLanguage.setText(_translate("Dialog", "Язык/Language:"))
        self.techRButton.setText(_translate("Dialog", "teachRadioButton"))
        self.examRButton.setText(_translate("Dialog", "examRadioButton"))
        self.modeLabel.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">modeLabel</p></body></html>"))
